In [16]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import Model
from keras.layers import Dense,Input,Dropout


In [17]:
data_train=pd.read_csv('/content/trainset.csv')
data_test=pd.read_csv('/content/testset.csv')

In [18]:
train=data_train.iloc[:,1:2]

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Open    1259 non-null   float64
dtypes: float64(1)
memory usage: 10.0 KB


In [20]:
train=train.astype('float32')

In [21]:
from sklearn.preprocessing import MinMaxScaler
MM=MinMaxScaler(feature_range=(0,1))
train_scaled=MM.fit_transform(train)

In [22]:
train_scaled

array([[0.01011148],
       [0.01388615],
       [0.01690727],
       ...,
       [0.97543955],
       [0.9674549 ],
       [0.9607252 ]], dtype=float32)

In [23]:
train_scaled.shape

(1259, 1)

In [24]:
x_train = []
y_train = []

In [25]:
for i in range(60,1259):
    x_train.append(train_scaled[i-60:i, 0])
    y_train.append(train_scaled[i,0])
x_train,y_train = np.array(x_train),np.array(y_train)

In [26]:
x_train.shape

(1199, 60)

In [27]:
y_train.shape

(1199,)

In [28]:
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))
print(x_train)

[[[0.01011148]
  [0.01388615]
  [0.01690727]
  ...
  [0.07456192]
  [0.06988981]
  [0.06804702]]

 [[0.01388615]
  [0.01690727]
  [0.02109298]
  ...
  [0.06988981]
  [0.06804702]
  [0.06189516]]

 [[0.01690727]
  [0.02109298]
  [0.02115461]
  ...
  [0.06804702]
  [0.06189516]
  [0.06842378]]

 ...

 [[0.8411081 ]
  [0.8328614 ]
  [0.8369986 ]
  ...
  [0.9858649 ]
  [0.9805695 ]
  [0.9763771 ]]

 [[0.8328614 ]
  [0.8369986 ]
  [0.83491623]
  ...
  [0.9805695 ]
  [0.9763771 ]
  [0.97543955]]

 [[0.8369986 ]
  [0.83491623]
  [0.8503752 ]
  ...
  [0.9763771 ]
  [0.97543955]
  [0.9674549 ]]]


In [30]:
import keras
from keras.models import Sequential,Model
inputs = keras.layers.Input(shape=(60,1))
lstm_out = keras.layers.LSTM(20,return_sequences=True)(inputs)
lstm_out = keras.layers.LSTM(40,return_sequences=True)(lstm_out)
lstm_out = keras.layers.LSTM(50,return_sequences=True)(lstm_out)
lstm_out = keras.layers.LSTM(70,return_sequences=True)(lstm_out)
lstm_out = keras.layers.LSTM(80,return_sequences=True)(lstm_out)
lstm_out = keras.layers.LSTM(100,return_sequences=True)(lstm_out)
outputs = keras.layers.Dense(1)(lstm_out)

model = keras.Model(inputs=inputs, outputs=outputs)

In [31]:
model.compile(optimizer='adam',loss='binary_crossentropy')

In [32]:
model.fit(x_train,x_train,epochs=10)

Epoch 1/10
38/38 [==============================] - 17s 21ms/step - loss: 0.9384
Epoch 2/10
38/38 [==============================] - 1s 19ms/step - loss: 0.6482
Epoch 3/10
38/38 [==============================] - 1s 18ms/step - loss: 0.6194
Epoch 4/10
38/38 [==============================] - 1s 18ms/step - loss: 0.6092
Epoch 5/10
38/38 [==============================] - 1s 25ms/step - loss: 0.6036
Epoch 6/10
38/38 [==============================] - 1s 26ms/step - loss: 0.5997
Epoch 7/10
38/38 [==============================] - 1s 24ms/step - loss: 0.6040
Epoch 8/10
38/38 [==============================] - 1s 19ms/step - loss: 0.5947
Epoch 9/10
38/38 [==============================] - 1s 19ms/step - loss: 0.5896
Epoch 10/10
38/38 [==============================] - 1s 19ms/step - loss: 0.5873


In [33]:
data_test

Date         Open         High  ...        Close    Adj Close   Volume
0    2018-01-02  1048.339966  1066.939941  ...  1065.000000  1065.000000  1237600
1    2018-01-03  1064.310059  1086.290039  ...  1082.479980  1082.479980  1430200
2    2018-01-04  1088.000000  1093.569946  ...  1086.400024  1086.400024  1004600
3    2018-01-05  1094.000000  1104.250000  ...  1102.229980  1102.229980  1279100
4    2018-01-08  1102.229980  1111.270020  ...  1106.939941  1106.939941  1047600
..          ...          ...          ...  ...          ...          ...      ...
120  2018-06-25  1143.599976  1143.910034  ...  1124.810059  1124.810059  2157300
121  2018-06-26  1128.000000  1133.209961  ...  1118.459961  1118.459961  1563200
122  2018-06-27  1121.339966  1131.836060  ...  1103.979980  1103.979980  1293900
123  2018-06-28  1102.089966  1122.310059  ...  1114.219971  1114.219971  1072400
124  2018-06-29  1120.000000  1128.227051  ...  1115.650024  1115.650024  1315100

[125 rows x 7 columns]

In [42]:
test=data_test.iloc[:,1:2]

In [43]:
test

Open
0    1048.339966
1    1064.310059
2    1088.000000
3    1094.000000
4    1102.229980
..           ...
120  1143.599976
121  1128.000000
122  1121.339966
123  1102.089966
124  1120.000000

[125 rows x 1 columns]

In [44]:
test=test.astype('float32')

In [45]:
test_scaled=MM.fit_transform(test)


In [46]:
test_scaled

array([[0.2986622 ],
       [0.38549376],
       [0.51429987],
       [0.5469227 ],
       [0.59167004],
       [0.6306548 ],
       [0.56377745],
       [0.6137996 ],
       [0.592649  ],
       [0.7563071 ],
       [0.7221074 ],
       [0.75032616],
       [0.7526097 ],
       [0.78338385],
       [0.9049587 ],
       [0.9999995 ],
       [0.97390175],
       [0.98776627],
       [0.9953785 ],
       [0.9483466 ],
       [0.96324444],
       [0.91996527],
       [0.6991625 ],
       [0.5284362 ],
       [0.18361282],
       [0.47917604],
       [0.33710337],
       [0.1296215 ],
       [0.29681396],
       [0.28050232],
       [0.3019786 ],
       [0.46574545],
       [0.5165291 ],
       [0.5282726 ],
       [0.6147237 ],
       [0.6675725 ],
       [0.6482711 ],
       [0.7306981 ],
       [0.8037734 ],
       [0.70476294],
       [0.6223359 ],
       [0.32443428],
       [0.4443779 ],
       [0.57530403],
       [0.5207696 ],
       [0.6628423 ],
       [0.77528286],
       [0.926

In [47]:
test_scaled.shape

(125, 1)

In [49]:
x_test=[]
y_test=[]

In [50]:
for i in range(60,125):
    x_test.append(test_scaled[i-60:i, 0])
    y_test.append(test_scaled[i,0])
x_test,y_test = np.array(x_test),np.array(y_test)

In [51]:
x_test.shape

(65, 60)

In [52]:
model.evaluate(x_test, x_test, verbose=0)

0.7105180025100708